---

- name: Add Stackdriver public key
  apt_key: url={{ stackdriver_pubkey_url }} state=present
  tags: ['stackdriver', 'stackdriver:install']

- name: Add Stackdriver repository
  apt_repository: >
    repo="deb {{ stackdriver_repo_url }} {{ stackdriver_distro_codename }} main"
    update_cache=yes
  tags: ['stackdriver', 'stackdriver:install']

- name: Install Stackdriver agent
  apt: name=stackdriver-agent
  tags: ['stackdriver', 'stackdriver:install']

- name: Copy Stackdriver configuration
  template: src="{{ stackdriver_agent_config }}" dest=/etc/default/stackdriver-agent
  notify: restart stackdriver
  tags: ['stackdriver', 'stackdriver:configuration']

- name: Trigger handler to restart stackdriver agent
  command: "/bin/true"
  notify: restart stackdriver
  when: stackdriver_restart
  tags: ['stackdriver', 'stackdriver:configuration']
